import type {
  Analysis,
  Domain,
  Finding,
  ForecastResponse,
  Project,
  Workflow,
} from "@/lib/api";

export const DEMO_PROJECT: Project = {
  id: "demo-product-launch",
  name: "Product Launch",
  description:
    "Demo workflow showing how FlowTrace connects work, dependencies, bottlenecks and downstream impact.",
  goal: "Launch the new product on schedule.",
  domain_id: "demo-product",
  start_date: "2026-09-01",
  deadline: "2026-09-30",
  today_day: 10,
  current_version_id: "demo-version-1",
};

export const DEMO_DOMAIN: Domain = {
  id: "demo-product",
  key: "product_launch",
  name: "Product Launch",
  description: "Demo product launch workflow.",
  vocabulary_hints: ["launch", "review", "QA", "release"],
  task_templates: [
    { name: "Market analysis", effort: 2 },
    { name: "Product review", effort: 3 },
    { name: "Build release", effort: 5 },
    { name: "QA approval", effort: 2 },
    { name: "Launch preparation", effort: 2 },
  ],
  duration_variance_prior: 0.2,
  is_custom: false,
};

export const DEMO_WORKFLOW: Workflow = {
  project_id: DEMO_PROJECT.id,
  project_name: DEMO_PROJECT.name,
  goal: DEMO_PROJECT.goal,
  project_start: DEMO_PROJECT.start_date,
  deadline: DEMO_PROJECT.deadline,
  deadline_day: 30,
  today_day: 10,
  version: {
    id: "demo-version-1",
    version_no: 1,
    parent_version_id: null,
    content_hash: "demo-workflow",
    is_draft: true,
    note: "Frontend demo workflow",
    created_at: "2026-09-10T00:00:00Z",
  },
  tasks: [
    {
      key: "research",
      name: "Market analysis",
      description: "Understand the market and customer requirements.",
      effort: 2,
      divisible: false,
      priority: 1,
      optimistic: 1,
      likely: 2,
      pessimistic: 3,
      required_skills: ["research"],
      status: "done",
      assignees: [{ key: "research", label: "Research" }],
    },
    {
      key: "design",
      name: "Product review",
      description: "Review the product design before development.",
      effort: 3,
      divisible: false,
      priority: 2,
      optimistic: 2,
      likely: 3,
      pessimistic: 5,
      required_skills: ["design"],
      status: "in_review",
      assignees: [{ key: "design", label: "Design" }],
    },
    {
      key: "development",
      name: "Build release",
      description: "Implement the product release.",
      effort: 5,
      divisible: false,
      priority: 1,
      optimistic: 4,
      likely: 5,
      pessimistic: 7,
      required_skills: ["development"],
      status: "in_progress",
      assignees: [{ key: "engineering", label: "Engineering" }],
    },
    {
      key: "qa",
      name: "QA approval",
      description: "Validate the release before launch.",
      effort: 2,
      divisible: false,
      priority: 1,
      optimistic: 1,
      likely: 2,
      pessimistic: 3,
      required_skills: ["qa"],
      status: "not_started",
      assignees: [{ key: "qa", label: "QA" }],
    },
    {
      key: "launch",
      name: "Launch preparation",
      description: "Prepare the final launch and release communications.",
      effort: 2,
      divisible: false,
      priority: 1,
      optimistic: 1,
      likely: 2,
      pessimistic: 3,
      required_skills: ["launch"],
      status: "not_started",
      assignees: [{ key: "launch", label: "Launch" }],
    },
  ],
  dependencies: [
    {
      from_task: "research",
      to_task: "design",
      dep_type: "finish_to_start",
      consumes: false,
    },
    {
      from_task: "design",
      to_task: "development",
      dep_type: "finish_to_start",
      consumes: true,
    },
    {
      from_task: "development",
      to_task: "qa",
      dep_type: "finish_to_start",
      consumes: false,
    },
    {
      from_task: "qa",
      to_task: "launch",
      dep_type: "finish_to_start",
      consumes: false,
    },
  ],
  resources: [
    {
      key: "research",
      name: "Research",
      kind: "team",
      capacity: 1,
      skills: ["research"],
      parent_key: null,
      label: "Research",
    },
    {
      key: "design",
      name: "Design",
      kind: "team",
      capacity: 1,
      skills: ["design"],
      parent_key: null,
      label: "Design",
    },
    {
      key: "engineering",
      name: "Engineering",
      kind: "team",
      capacity: 2,
      skills: ["development"],
      parent_key: null,
      label: "Engineering",
    },
    {
      key: "qa",
      name: "QA",
      kind: "team",
      capacity: 1,
      skills: ["qa"],
      parent_key: null,
      label: "QA",
    },
    {
      key: "launch",
      name: "Launch",
      kind: "team",
      capacity: 1,
      skills: ["launch"],
      parent_key: null,
      label: "Launch",
    },
  ],
  requirements: [
    {
      key: "REQ-001",
      version_no: 1,
      text: "Product must be ready for launch.",
      consumed_by: ["design", "development", "qa"],
    },
  ],
  constraints: [
    {
      kind: "deadline",
      target: "launch",
      reason: "Launch must happen by the project deadline.",
      value: 30,
    },
  ],
};

const demoImpact = {
  score: 72,
  magnitude: 4,
  magnitude_kind: "days",
  magnitude_label: "4 downstream days",
  downstream_affected: 3,
  formula: "impact = magnitude × downstream reach",
  worked: "4 days × 3 affected tasks",
};

const demoFinding: Finding = {
  kind: "dependency_chain_risk",
  tier: 2,
  tier_name: "Dependency",
  severity: "medium",
  task_ids: ["design", "development", "qa"],
  root_cause: "design",
  evidence: {
    reason: "Product review gates the development release.",
  },
  impact_score: 72,
  impact: demoImpact,
  downstream_affected: ["development", "qa", "launch"],
  suggested_action: "Complete the product review before development slips.",
  explanation:
    "A delay in the product review propagates through the release and QA chain.",
  suppressed: null,
};

const analysisTasks: Analysis["tasks"] = [
  {
    key: "research",
    name: "Market analysis",
    effort: 2,
    duration: 2,
    status: "done",
    assignees: ["Research"],
    es: 1,
    ef: 2,
    ls: 1,
    lf: 2,
    slack: 0,
    critical: true,
    start_date: "2026-09-01",
    end_date: "2026-09-02",
    depends_on: [],
  },
  {
    key: "design",
    name: "Product review",
    effort: 3,
    duration: 3,
    status: "in_review",
    assignees: ["Design"],
    es: 3,
    ef: 5,
    ls: 3,
    lf: 5,
    slack: 0,
    critical: true,
    start_date: "2026-09-03",
    end_date: "2026-09-05",
    depends_on: ["research"],
  },
  {
    key: "development",
    name: "Build release",
    effort: 5,
    duration: 5,
    status: "in_progress",
    assignees: ["Engineering"],
    es: 6,
    ef: 10,
    ls: 6,
    lf: 10,
    slack: 0,
    critical: true,
    start_date: "2026-09-06",
    end_date: "2026-09-10",
    depends_on: ["design"],
  },
  {
    key: "qa",
    name: "QA approval",
    effort: 2,
    duration: 2,
    status: "not_started",
    assignees: ["QA"],
    es: 11,
    ef: 12,
    ls: 11,
    lf: 12,
    slack: 0,
    critical: true,
    start_date: "2026-09-11",
    end_date: "2026-09-12",
    depends_on: ["development"],
  },
  {
    key: "launch",
    name: "Launch preparation",
    effort: 2,
    duration: 2,
    status: "not_started",
    assignees: ["Launch"],
    es: 13,
    ef: 14,
    ls: 13,
    lf: 14,
    slack: 0,
    critical: true,
    start_date: "2026-09-13",
    end_date: "2026-09-14",
    depends_on: ["qa"],
  },
];

export const DEMO_ANALYSIS: Analysis = {
  analysis_run_id: "demo-analysis-1",
  engine_version: "flowtrace-demo",
  input_hash: "demo-workflow",
  schedulable: true,
  cycles: [],
  project_id: DEMO_PROJECT.id,
  project_name: DEMO_PROJECT.name,
  version_id: "demo-version-1",
  version_no: 1,
  project_start: "2026-09-01",
  today_day: 10,
  planned_end: 14,
  projected_end: 16,
  slip_days: 2,
  planned_end_date: "2026-09-14",
  projected_end_date: "2026-09-16",
  deadline_date: "2026-09-30",
  critical_path: ["research", "design", "development", "qa", "launch"],
  tasks: analysisTasks,
  resources: [
    {
      key: "research",
      name: "Research",
      label: "Research",
      kind: "team",
      capacity: 1,
      parent_key: null,
    },
    {
      key: "design",
      name: "Design",
      label: "Design",
      kind: "team",
      capacity: 1,
      parent_key: null,
    },
    {
      key: "engineering",
      name: "Engineering",
      label: "Engineering",
      kind: "team",
      capacity: 2,
      parent_key: null,
    },
    {
      key: "qa",
      name: "QA",
      label: "QA",
      kind: "team",
      capacity: 1,
      parent_key: null,
    },
    {
      key: "launch",
      name: "Launch",
      label: "Launch",
      kind: "team",
      capacity: 1,
      parent_key: null,
    },
  ],
  edges: DEMO_WORKFLOW.dependencies.map((d) => ({
    source: d.from_task,
    target: d.to_task,
    dep_type: d.dep_type,
    consumes: d.consumes,
  })),
  findings: [demoFinding],
  suppressed_findings: [],
  finding_counts_by_tier: {
    "1": 0,
    "2": 1,
    "3": 0,
  },
  feasibility: {
    verdict: "on_track",
    deadline_day: 30,
    projected_end_day: 16,
    margin_days: 14,
    statement: "The workflow is projected to finish 14 days before the deadline.",
    three_point: {
      optimistic_day: 13,
      likely_day: 16,
      pessimistic_day: 20,
      spread_days: 7,
      deadline_day: 30,
      verdicts: {
        optimistic: "on_track",
        likely: "on_track",
        pessimistic: "on_track",
      },
      assumptions: {
        note: "Demo three-point estimate.",
      },
      is_probability: false,
      method: "three_point_estimate",
      monte_carlo: {
        available: false,
        why: "Demo data does not run Monte Carlo.",
        what_it_would_report: "A calibrated completion distribution.",
        why_not_faked: "No probability is presented as real demo evidence.",
      },
    },
    is_probability: false,
  },
  effort_model: {
    formula: "duration = effort / effective capacity",
    efficiency: 1,
    non_divisible_tasks: ["research", "design", "development", "qa", "launch"],
    note: "Frontend demonstration only.",
  },
  config: {
    mode: "demo",
    duration_variance_prior: 0.2,
  },
  tier_reached: 2,
  checks_run: ["dependency_chain", "deadline"],
  unavailable_checks: [],
  resource_unavailability: {
    adjustments: [],
    total_days_added: 0,
    method: "demo",
    is_approximation: true,
  },
  risk: {
    tasks: [
      {
        task_key: "design",
        task_name: "Product review",
        score: 68,
        band: "medium",
        score_kind: "risk_score",
        formula: "weighted risk factors",
        factors: [
          {
            name: "criticality",
            value: 0.9,
            weight: 0.5,
            contribution: 0.45,
            reason: "The task lies on the critical path.",
            evidence: { critical: true },
            tier: 1,
            available: true,
          },
          {
            name: "duration_spread",
            value: 0.6,
            weight: 0.3,
            contribution: 0.18,
            reason: "Three-point estimates have meaningful spread.",
            evidence: { spread_days: 3 },
            tier: 1,
            available: true,
          },
        ],
        explanation: "Product review has elevated risk because it gates development.",
        top_factors: ["criticality", "duration_spread"],
      },
      {
        task_key: "development",
        task_name: "Build release",
        score: 61,
        band: "medium",
        score_kind: "risk_score",
        formula: "weighted risk factors",
        factors: [
          {
            name: "criticality",
            value: 0.9,
            weight: 0.5,
            contribution: 0.45,
            reason: "The task lies on the critical path.",
            evidence: { critical: true },
            tier: 1,
            available: true,
          },
        ],
        explanation: "Build release is critical to the QA and launch chain.",
        top_factors: ["criticality"],
      },
      {
        task_key: "qa",
        task_name: "QA approval",
        score: 44,
        band: "low",
        score_kind: "risk_score",
        formula: "weighted risk factors",
        factors: [],
        explanation: "QA follows development and has a short estimated duration.",
        top_factors: [],
      },
    ],
    top: [],
    band_counts: {
      low: 1,
      medium: 2,
      high: 0,
    },
    assumptions: {
      score_kind: "risk_score",
      disclaimer: "This is a demo risk score, not a probability.",
      formula: "weighted risk factors",
      weights: {
        criticality: 0.5,
        duration_spread: 0.3,
        downstream_impact: 0.2,
      },
      weights_total: 1,
      duration_spread: {
        relative_spread: 0.2,
        provenance: "demo",
        tasks_with_three_point_estimate: ["design", "development", "qa"],
        tasks_using_spread_prior: [],
      },
      factors_unavailable: [],
      factors_unavailable_note: "",
      rework_modelled: false,
      monte_carlo_run: false,
      what_would_make_this_a_probability:
        "Calibration against historical labelled outcomes would be required.",
    },
  },
};

DEMO_ANALYSIS.risk.top = [...DEMO_ANALYSIS.risk.tasks].sort(
  (a, b) => b.score - a.score,
);

const histogramBins = [
  {
    from_day: 13,
    to_day: 14,
    from_date: "2026-09-13",
    to_date: "2026-09-14",
    count: 120,
    share: 0.12,
    cumulative_share: 0.12,
  },
  {
    from_day: 15,
    to_day: 16,
    from_date: "2026-09-15",
    to_date: "2026-09-16",
    count: 430,
    share: 0.43,
    cumulative_share: 0.55,
  },
  {
    from_day: 17,
    to_day: 18,
    from_date: "2026-09-17",
    to_date: "2026-09-18",
    count: 300,
    share: 0.3,
    cumulative_share: 0.85,
  },
  {
    from_day: 19,
    to_day: 21,
    from_date: "2026-09-19",
    to_date: "2026-09-21",
    count: 150,
    share: 0.15,
    cumulative_share: 1,
  },
];

export const DEMO_FORECAST: ForecastResponse = {
  project_id: DEMO_PROJECT.id,
  project_name: DEMO_PROJECT.name,
  version_id: "demo-version-1",
  version_no: 1,
  project_start: "2026-09-01",
  today_day: 10,
  deadline_date: "2026-09-30",
  engine_version: "flowtrace-demo",
  input_hash: "demo-workflow",
  tier_reached: 2,
  schedulable: true,
  answer_kind: "structural_estimate",
  answer_kind_note:
    "This frontend demo uses a structural estimate rather than a calibrated probability.",
  forecast: {
    kind: "demo_structural_forecast",
    available: true,
    is_probability: false,
    is_calibrated: false,
    disclaimer:
      "Demo forecast values are illustrative and are not calibrated probabilities.",
    what_would_calibrate_it:
      "Historical labelled project outcomes would be required.",
    not_the_structural_estimate:
      "This demo is intentionally illustrative.",
    iterations: 1000,
    seed: 42,
    distribution: "demo_three_point_distribution",
    completion: {
      p50_day: 16,
      p50_date: "2026-09-16",
      p80_day: 18,
      p80_date: "2026-09-18",
      p90_day: 20,
      p90_date: "2026-09-20",
      mean_day: 16.7,
      mean_date: "2026-09-17",
      earliest_day: 13,
      earliest_date: "2026-09-13",
      latest_day: 21,
      latest_date: "2026-09-21",
    },
    deadline: {
      deadline_day: 30,
      deadline_date: "2026-09-30",
      probability_of_meeting_deadline: 0.98,
      iterations_meeting_deadline: 980,
      band: "very_likely",
      band_note:
        "Illustrative demo band; it is not a calibrated probability.",
    },
    histogram: {
      bins: histogramBins,
      bin_count: histogramBins.length,
      bin_width_days: 2,
      method: "demo",
    },
    tasks: [
      {
        task_key: "research",
        task_name: "Market analysis",
        criticality_index: 0.72,
        iterations_on_critical_path: 720,
        mean_duration_days: 2,
        assumed: false,
        criticality_means: "Usually critical in the demo chain.",
        duration: {
          optimistic_days: 1,
          likely_days: 2,
          pessimistic_days: 3,
          relative_spread: 1,
          spread_provenance: "three_point_estimate",
          assumed: false,
        },
      },
      {
        task_key: "design",
        task_name: "Product review",
        criticality_index: 0.94,
        iterations_on_critical_path: 940,
        mean_duration_days: 3.2,
        assumed: false,
        criticality_means: "Highly critical because it gates development.",
        duration: {
          optimistic_days: 2,
          likely_days: 3,
          pessimistic_days: 5,
          relative_spread: 1,
          spread_provenance: "three_point_estimate",
          assumed: false,
        },
      },
      {
        task_key: "development",
        task_name: "Build release",
        criticality_index: 0.97,
        iterations_on_critical_path: 970,
        mean_duration_days: 5.2,
        assumed: false,
        criticality_means: "Almost always critical in the demo chain.",
        duration: {
          optimistic_days: 4,
          likely_days: 5,
          pessimistic_days: 7,
          relative_spread: 3,
          spread_provenance: "three_point_estimate",
          assumed: false,
        },
      },
      {
        task_key: "qa",
        task_name: "QA approval",
        criticality_index: 0.84,
        iterations_on_critical_path: 840,
        mean_duration_days: 2.1,
        assumed: false,
        criticality_means: "Usually critical before launch.",
        duration: {
          optimistic_days: 1,
          likely_days: 2,
          pessimistic_days: 3,
          relative_spread: 1,
          spread_provenance: "three_point_estimate",
          assumed: false,
        },
      },
      {
        task_key: "launch",
        task_name: "Launch preparation",
        criticality_index: 0.79,
        iterations_on_critical_path: 790,
        mean_duration_days: 2,
        assumed: false,
        criticality_means: "Downstream task that closes the chain.",
        duration: {
          optimistic_days: 1,
          likely_days: 2,
          pessimistic_days: 3,
          relative_spread: 1,
          spread_provenance: "three_point_estimate",
          assumed: false,
        },
      },
    ],
    assumptions: {
      note: "Illustrative frontend demo forecast.",
    },
  },
  structural_risk: {
    score_kind: "risk_score",
    is_probability: false,
    disclaimer: "Risk score is not a probability.",
    band_counts: {
      low: 1,
      medium: 2,
      high: 0,
    },
    top: [
      {
        task_key: "development",
        task_name: "Build release",
        score: 61,
        band: "medium",
      },
      {
        task_key: "design",
        task_name: "Product review",
        score: 68,
        band: "medium",
      },
    ],
    assumptions: {
      note: "Demo structural risk.",
    },
  },
  deterministic: {
    projected_end_day: 16,
    projected_end_date: "2026-09-16",
    planned_end_day: 14,
    slip_days: 2,
    feasibility: DEMO_ANALYSIS.feasibility,
    note: "Demo deterministic estimate.",
  },
};
